baseURL = 'https://kodeblog.netlify.app/'
languageCode = 'id-id'
title = 'Blog kode'
theme = "fresh"
summaryLength= 1
paginate= 6
    [params]
        Description ="membantu pemula untuk belajar bahasa pemrograman web"
    [taxonomy]
        tag ="tags"
        category ="categories"
    [Search]
        keywords = "Pengenalan Hugo"