[build]
publish = "public"
command = "git submodule update -f --init && hugo --gc --minify"


[context.production.enviroment]
HUGO_VERSION = "0.101.0"
HUGO_ENV  = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.enviroment]
HUGO_VERSION = "0.101.0"
HUGO_ENV    = "production"

[context.deploy.preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.enviroment]
HUGO_VERSION = "0.101.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.enviroment]
HUGO_VERSION = "0.101.0"

[context.next.enviroment]
HUGO_ENABLEGITINFO = "true"
